# Generated by Django 4.2.29 on 2026-03-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('grade_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(related_name='students_enrolled', through='enrollments.Enrollment', to='courses.course')),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
