# Generated by Django 4.2.29 on 2026-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('courses', '0002_course_students'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students_enrolled', through='enrollments.Enrollment', to='courses.course'),
        ),
    ]
