# Generated by Django 4.2.29 on 2026-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='TEMP', help_text='Unique Identifier for the Student', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
