# Generated by Django 4.2.29 on 2026-03-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the course session.')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', help_text='Attendance status for this session.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes (e.g. reason for absence).')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
