# Generated by Django 4.2.29 on 2026-03-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(help_text='The enrollment this attendance record is tied to.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='enrollments.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
    ]
